### ISSUE TITLE
Travis build is broken: Seems like etcd is missing?

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/loggregatorlib#12]
Here is what the build log says:

```
$ pushd $HOME/gopath/src/github.com/coreos/etcd && git checkout v0.4.6 && ./build && go install && popd
/home/travis/build.sh: line 41: pushd: /home/travis/gopath/src/github.com/coreos/etcd: No such file or directory
The command "pushd $HOME/gopath/src/github.com/coreos/etcd && git checkout v0.4.6 && ./build && go install && popd" failed and exited with 1 during .
```

**Comment by jmtuley** [comment]
Looks like we were relying on go-etcd to depend on etcd, which is no longer the case.

**Comment by voelzmo** [comment]
Thanks @jmtuley that fixes the build. Those steps should probably be included in the README.md as well, as it is required for developers to run the tests.

**Comment by jmtuley** [comment]
Good point; we'll are care of that.

On Friday, April 24, 2015, Marco Voelz <notifications@github.com> wrote:

> Thanks @jmtuley <https://github.com/jmtuley> that fixes the build. Those
> steps should probably be included in the README.md as well, as it is
> required for developers to run the tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/loggregatorlib/issues/12#issuecomment-95908643>
> .
>


-- 
– John Tuley
